import { neon } from '@neondatabase/serverless';
const sql = neon(process.env.NEON_DB_KEY);

// city_id map: Scottsdale=1, Sedona=2, Tucson=3, Phoenix=4, Flagstaff=5
//              Santa Fe=6, Taos=7, Albuquerque=8, Denver=9, Aspen=10
//              Boulder=11, Las Vegas=12, Salt Lake City=13, Moab=14, Marfa=18
// listing_id: Heard Museum=34, Phoenix Art Museum=33, Aspen Art Museum=87,
//             Chinati Foundation=99, Georgia O'Keeffe Museum=49

const events = [
  // ── Recurring monthly / weekly ─────────────────────────────────────────────
  {
    title: 'Scottsdale ArtWalk',
    slug: 'scottsdale-artwalk-thursday',
    description: 'Every Thursday evening from October through May, Old Town Scottsdale gallery district stays open until 9pm. Dozens of galleries host opening receptions, artists appear in person, and the streets fill with collectors and curious visitors. One of the longest-running gallery walks in the country — free and open to all.',
    event_date: '2026-05-21',
    start_time: '19:00',
    end_time: '21:00',
    city_id: 1, state_code: 'AZ', is_recurring: true,
    recurrence_rule: 'FREQ=WEEKLY;BYDAY=TH;MONTHS=10,11,12,1,2,3,4,5',
    is_free: true,
    website_url: 'https://www.scottsdalegalleries.com',
    meta_title: 'Scottsdale ArtWalk | Thursday Gallery Night | Southwest Galleries',
    meta_description: 'The Scottsdale ArtWalk happens every Thursday evening in Old Town. Dozens of galleries open simultaneously for one of America\'s premier gallery walks.',
  },
  {
    title: 'Phoenix First Friday Art Walk',
    slug: 'phoenix-first-friday-art-walk',
    description: 'On the first Friday of every month, the Roosevelt Row Arts District in Phoenix comes alive from 6–10pm. Galleries, studios, and pop-up exhibitions open simultaneously, street vendors fill the sidewalks, and local musicians perform. One of the most-attended public art events in Arizona, drawing thousands each month to the city\'s creative core.',
    event_date: '2026-06-05',
    start_time: '18:00',
    end_time: '22:00',
    city_id: 4, state_code: 'AZ', is_recurring: true,
    recurrence_rule: 'FREQ=MONTHLY;BYDAY=1FR',
    is_free: true,
    website_url: 'https://rooseveltrow.org',
    meta_title: 'Phoenix First Friday Art Walk | Roosevelt Row | Southwest Galleries',
    meta_description: 'Phoenix First Friday happens the first Friday of every month in the Roosevelt Row Arts District — galleries, music, food, and thousands of art lovers.',
  },
  {
    title: 'Denver First Friday Art Walk',
    slug: 'denver-first-friday-art-walk',
    description: 'Denver\'s First Friday Art Walk on the first Friday of each month (6–9pm) covers both the Santa Fe Arts District and RiNo Arts District simultaneously. Galleries open their doors, new shows debut, and the creative energy of the city concentrates into a few vibrant blocks. The Santa Fe Drive corridor has been the anchor for decades; RiNo adds a younger, more experimental counterpoint.',
    event_date: '2026-06-05',
    start_time: '18:00',
    end_time: '21:00',
    city_id: 9, state_code: 'CO', is_recurring: true,
    recurrence_rule: 'FREQ=MONTHLY;BYDAY=1FR',
    is_free: true,
    website_url: 'https://www.denverfirstfriday.com',
    meta_title: 'Denver First Friday Art Walk | Santa Fe Arts District | Southwest Galleries',
    meta_description: 'Denver First Friday happens every month across the Santa Fe Arts District and RiNo — open galleries, new shows, and the city\'s creative community.',
  },
  {
    title: 'Tucson First Thursdays',
    slug: 'tucson-first-thursdays-art-walk',
    description: 'Tucson\'s First Thursdays art walk animates the downtown arts district on the first Thursday of every month. Galleries in the downtown corridor, the 4th Avenue neighborhood, and the university area stay open late. The crowd is characteristically local — artists, students, and longtime collectors who have made this a genuine community ritual rather than a tourist event.',
    event_date: '2026-06-04',
    start_time: '18:00',
    end_time: '21:00',
    city_id: 3, state_code: 'AZ', is_recurring: true,
    recurrence_rule: 'FREQ=MONTHLY;BYDAY=1TH',
    is_free: true,
    website_url: 'https://www.artscorptucson.org',
    meta_title: 'Tucson First Thursdays Art Walk | Downtown Arts District | Southwest Galleries',
    meta_description: 'Tucson First Thursdays happens the first Thursday of every month in the downtown arts district — galleries, artists, and Tucson\'s creative community.',
  },
  {
    title: 'Santa Fe First Fridays',
    slug: 'santa-fe-first-fridays',
    description: 'Santa Fe galleries across Canyon Road and the Railyard Arts District host simultaneous opening receptions on the first Friday of each month. The Canyon Road Friday openings are a long tradition — galleries stay open until 7pm or later, artists appear in person, and the street fills with pedestrians moving from space to space. The Railyard adds a contemporary counterpoint with a younger gallery roster.',
    event_date: '2026-06-05',
    start_time: '17:00',
    end_time: '19:00',
    city_id: 6, state_code: 'NM', is_recurring: true,
    recurrence_rule: 'FREQ=MONTHLY;BYDAY=1FR',
    is_free: true,
    website_url: 'https://www.santafe.org/arts/',
    meta_title: 'Santa Fe First Fridays | Canyon Road Gallery Openings | Southwest Galleries',
    meta_description: 'Santa Fe First Fridays: Canyon Road and Railyard galleries host simultaneous opening receptions monthly — free, open to all.',
  },
  {
    title: 'Albuquerque Arts Walk',
    slug: 'albuquerque-arts-walk-monthly',
    description: 'Albuquerque\'s monthly Arts Walk covers the Nob Hill corridor along Central Avenue (old Route 66), the downtown Arts & Cultural District, and the Old Town galleries. On the second Friday of each month, participating galleries stay open late and often host demonstrations, artist talks, and live music. A community-focused event with a price of admission that makes it accessible to everyone.',
    event_date: '2026-06-12',
    start_time: '17:00',
    end_time: '20:00',
    city_id: 8, state_code: 'NM', is_recurring: true,
    recurrence_rule: 'FREQ=MONTHLY;BYDAY=2FR',
    is_free: true,
    website_url: 'https://www.albuquerquearts.com',
    meta_title: 'Albuquerque Arts Walk | Monthly Gallery Night | Southwest Galleries',
    meta_description: 'Albuquerque\'s monthly Arts Walk covers Nob Hill, downtown, and Old Town galleries on the second Friday of each month — free and open to all.',
  },
  {
    title: 'Salt Lake City Gallery Stroll',
    slug: 'salt-lake-city-gallery-stroll',
    description: 'Salt Lake City\'s Gallery Stroll, held the third Friday of each month, connects galleries across downtown, the Granary Arts District, and the Sugar House neighborhood. The event has grown steadily since its founding and now includes dozens of participating spaces, with the Utah Museum of Fine Arts and Phillips Gallery among the consistent anchors.',
    event_date: '2026-05-15',
    start_time: '18:00',
    end_time: '21:00',
    city_id: 13, state_code: 'UT', is_recurring: true,
    recurrence_rule: 'FREQ=MONTHLY;BYDAY=3FR',
    is_free: true,
    website_url: 'https://www.gaslamp.org',
    meta_title: 'Salt Lake City Gallery Stroll | Monthly Art Walk | Southwest Galleries',
    meta_description: 'Salt Lake City Gallery Stroll happens the third Friday of every month — connecting galleries across downtown, the Granary Arts District, and Sugar House.',
  },

  // ── Annual festivals and fairs ────────────────────────────────────────────
  {
    title: 'Santa Fe Indian Market',
    slug: 'santa-fe-indian-market-2026',
    description: 'The Santa Fe Indian Market, held annually on the weekend of the third Saturday of August on the historic Santa Fe Plaza, is the largest and most prestigious Native American art market in the world. More than 1,000 Native artists from 220+ tribes exhibit work across every medium — pottery, jewelry, weaving, painting, sculpture, and fashion. The weekend draws over 100,000 visitors and is the single most important event in the Native American art market calendar.',
    event_date: '2026-08-15',
    event_end_date: '2026-08-16',
    city_id: 6, state_code: 'NM', is_recurring: true,
    recurrence_rule: 'FREQ=YEARLY',
    is_free: true,
    website_url: 'https://swaia.org',
    meta_title: 'Santa Fe Indian Market 2026 | SWAIA | Southwest Galleries',
    meta_description: 'The Santa Fe Indian Market (August 2026) is the world\'s largest and most prestigious Native American art market — 1,000+ artists, 100,000+ visitors.',
  },
  {
    title: 'Heard Museum Guild Indian Fair & Market',
    slug: 'heard-museum-indian-fair-2027',
    description: 'Held annually in early March at the Heard Museum in Phoenix, the Heard Museum Guild Indian Fair & Market is the second-largest and among the most prestigious Native American art markets in the country. The juried exhibition brings together hundreds of Native artists, with strict quality standards that make it a reliable source for museum-quality work. The event includes cultural demonstrations, food, and live music alongside the market.',
    event_date: '2027-03-06',
    event_end_date: '2027-03-07',
    city_id: 4, state_code: 'AZ',
    listing_id: 34, is_recurring: true,
    recurrence_rule: 'FREQ=YEARLY',
    is_free: false,
    ticket_url: 'https://heard.org/event/indian-fair-market/',
    website_url: 'https://heard.org',
    meta_title: 'Heard Museum Guild Indian Fair & Market 2027 | Southwest Galleries',
    meta_description: 'The Heard Museum Indian Fair & Market (March 2027) is one of the most prestigious Native American art markets in the country — juried, museum-quality work.',
  },
  {
    title: 'Scottsdale Arts Festival',
    slug: 'scottsdale-arts-festival-2027',
    description: 'The Scottsdale Arts Festival, held annually in March at Scottsdale Civic Center Mall, is one of the top-ranked juried outdoor art festivals in the United States. More than 170 artists from across the country exhibit paintings, sculpture, photography, ceramics, jewelry, and glass — all juried for quality. The festival draws over 50,000 visitors over three days and is a significant collecting opportunity for work priced from under $100 to well over $10,000.',
    event_date: '2027-03-12',
    event_end_date: '2027-03-14',
    city_id: 1, state_code: 'AZ', is_recurring: true,
    recurrence_rule: 'FREQ=YEARLY',
    is_free: false,
    ticket_url: 'https://www.scottsdaleartsdistrict.org',
    website_url: 'https://www.scottsdaleartsdistrict.org',
    meta_title: 'Scottsdale Arts Festival 2027 | Juried Outdoor Art Festival | Southwest Galleries',
    meta_description: 'The Scottsdale Arts Festival (March 2027) is one of America\'s top juried outdoor art festivals — 170+ artists, 50,000+ visitors, Scottsdale Civic Center.',
  },
  {
    title: 'Cherry Creek Arts Festival',
    slug: 'cherry-creek-arts-festival-2026',
    description: 'The Cherry Creek Arts Festival, held annually over the Fourth of July weekend in Denver\'s Cherry Creek North neighborhood, is one of the top-ranked juried outdoor art festivals in the country. More than 250 artists exhibit work across all media over three days, drawing upwards of 350,000 visitors. The festival is complemented by performing arts programming and food, making it one of the signature summer events in the Rocky Mountain region.',
    event_date: '2026-07-03',
    event_end_date: '2026-07-05',
    city_id: 9, state_code: 'CO', is_recurring: true,
    recurrence_rule: 'FREQ=YEARLY',
    is_free: true,
    website_url: 'https://www.cherryarts.org',
    meta_title: 'Cherry Creek Arts Festival 2026 | Denver | Southwest Galleries',
    meta_description: 'Cherry Creek Arts Festival (July 4th weekend 2026) — one of America\'s top juried outdoor art festivals with 250+ artists in Denver\'s Cherry Creek North.',
  },
  {
    title: 'Taos Fall Arts Festival',
    slug: 'taos-fall-arts-festival-2026',
    description: 'The Taos Fall Arts Festival, held each September, is the town\'s premier annual gallery event — a two-week celebration of Taos\'s living arts community that includes studio tours, gallery openings, artist talks, and the Taos Art Auction. The festival spans the gallery district, surrounding studios, and Taos Pueblo itself, with a programming calendar that connects collectors directly with the artists who make Taos one of the most important art communities in the Southwest.',
    event_date: '2026-09-25',
    event_end_date: '2026-10-11',
    city_id: 7, state_code: 'NM', is_recurring: true,
    recurrence_rule: 'FREQ=YEARLY',
    is_free: true,
    website_url: 'https://taosarts.org',
    meta_title: 'Taos Fall Arts Festival 2026 | Studio Tours & Gallery Events | Southwest Galleries',
    meta_description: 'The Taos Fall Arts Festival (September–October 2026) is a two-week celebration of the Taos arts community — studio tours, gallery openings, and the Taos Art Auction.',
  },
  {
    title: 'Sedona Arts Festival',
    slug: 'sedona-arts-festival-2026',
    description: 'The Sedona Arts Festival, held each October in Sedona Heritage Park, draws over 60 juried artists to one of the most visually dramatic settings of any art fair in the country. The red rock backdrop of Cathedral Rock and Bell Rock creates a viewing environment that amplifies the impact of landscape painting and sculpture in particular. A two-day event with live music and food that consistently attracts serious collectors from across the region.',
    event_date: '2026-10-09',
    event_end_date: '2026-10-11',
    city_id: 2, state_code: 'AZ', is_recurring: true,
    recurrence_rule: 'FREQ=YEARLY',
    is_free: false,
    ticket_url: 'https://sedonaartsfestival.org',
    website_url: 'https://sedonaartsfestival.org',
    meta_title: 'Sedona Arts Festival 2026 | Juried Art Fair | Southwest Galleries',
    meta_description: 'The Sedona Arts Festival (October 2026) brings 60+ juried artists to Sedona Heritage Park against the backdrop of the red rocks.',
  },
  {
    title: 'Sedona Plein Air Festival',
    slug: 'sedona-plein-air-festival-2026',
    description: 'The Sedona Plein Air Festival gathers landscape painters from across the country each October to paint the red rock country en plein air — directly in front of the subject. The week-long event includes painting demonstrations, quick draw competitions (where artists have two hours to complete and sell a painting), gallery exhibitions, and a culminating Quick Draw & Sale. For collectors interested in traditional landscape painting, it\'s one of the most exciting events of the year.',
    event_date: '2026-10-16',
    event_end_date: '2026-10-24',
    city_id: 2, state_code: 'AZ', is_recurring: true,
    recurrence_rule: 'FREQ=YEARLY',
    is_free: true,
    website_url: 'https://sedonapleinair.com',
    meta_title: 'Sedona Plein Air Festival 2026 | Landscape Painting | Southwest Galleries',
    meta_description: 'The Sedona Plein Air Festival (October 2026) brings landscape painters to the red rocks for a week of painting demonstrations, quick draws, and gallery sales.',
  },
  {
    title: 'Chinati Foundation Open House',
    slug: 'chinati-foundation-open-house-2026',
    description: 'The Chinati Foundation Open House, held each October in Marfa, Texas, is the one weekend each year when the Foundation opens all of its permanent installations to the public simultaneously — including the 100 untitled aluminum works by Donald Judd that are normally accessible only via scheduled tour. The weekend includes artist talks, music, and social events that bring together an international community of artists, curators, and collectors in the remote West Texas landscape.',
    event_date: '2026-10-02',
    event_end_date: '2026-10-04',
    city_id: 18, state_code: 'TX',
    listing_id: 99, is_recurring: true,
    recurrence_rule: 'FREQ=YEARLY',
    is_free: false,
    ticket_url: 'https://chinati.org',
    website_url: 'https://chinati.org',
    meta_title: 'Chinati Foundation Open House 2026 | Marfa, TX | Southwest Galleries',
    meta_description: 'The Chinati Foundation Open House (October 2026) opens all installations simultaneously — Judd\'s 100 aluminum works, Flavin, Chamberlain, and more in Marfa, TX.',
  },
  {
    title: 'Arizona Fine Art Expo',
    slug: 'arizona-fine-art-expo-2027',
    description: 'The Arizona Fine Art Expo, held annually from January through March in Scottsdale, is the Southwest\'s largest juried fine art show — operating for 10 weeks in a purpose-built tent structure. Over 100 artists exhibit work in painting, sculpture, glass, and mixed media, with work available for direct purchase. The extended format makes it a destination for repeat visits as new work rotates in throughout the run.',
    event_date: '2027-01-16',
    event_end_date: '2027-03-28',
    city_id: 1, state_code: 'AZ', is_recurring: true,
    recurrence_rule: 'FREQ=YEARLY',
    is_free: false,
    ticket_url: 'https://www.arizonafineartexpo.com',
    website_url: 'https://www.arizonafineartexpo.com',
    meta_title: 'Arizona Fine Art Expo 2027 | Scottsdale | Southwest Galleries',
    meta_description: 'The Arizona Fine Art Expo (January–March 2027) is the Southwest\'s largest juried fine art show — 100+ artists, 10 weeks, direct purchase.',
  },
  {
    title: 'Aspen Art Museum Summer Opening',
    slug: 'aspen-art-museum-summer-2026',
    description: 'The Aspen Art Museum anchors the summer cultural season with its annual summer exhibition opening — typically in late June — which coincides with the beginning of the Aspen Ideas Festival and the Aspen Music Festival. The museum\'s Shigeru Ban building and no-permanent-collection model means the summer programming is always fresh, with international artists of significant reputation. Free admission year-round.',
    event_date: '2026-06-27',
    city_id: 10, state_code: 'CO',
    listing_id: 87, is_recurring: true,
    recurrence_rule: 'FREQ=YEARLY',
    is_free: true,
    website_url: 'https://www.aspenartmuseum.org',
    meta_title: 'Aspen Art Museum Summer Exhibition 2026 | Southwest Galleries',
    meta_description: 'The Aspen Art Museum Summer Opening (June 2026) kicks off the festival season with new international exhibitions in Shigeru Ban\'s landmark building. Free admission.',
  },
  {
    title: 'Moab Arts Festival',
    slug: 'moab-arts-festival-2026',
    description: 'The Moab Arts Festival, held each Memorial Day weekend in Swanny City Park, brings 100+ juried artists to one of the most spectacular natural settings of any art fair in the West. Situated between Arches National Park and Canyonlands, with the red rock walls of the Colorado River canyon as backdrop, the festival draws collectors who combine art shopping with outdoor recreation in the surrounding canyon country.',
    event_date: '2026-05-23',
    event_end_date: '2026-05-25',
    city_id: 14, state_code: 'UT', is_recurring: true,
    recurrence_rule: 'FREQ=YEARLY',
    is_free: false,
    ticket_url: 'https://moabartsfestival.org',
    website_url: 'https://moabartsfestival.org',
    meta_title: 'Moab Arts Festival 2026 | Memorial Day Weekend | Southwest Galleries',
    meta_description: 'The Moab Arts Festival (Memorial Day 2026) brings 100+ juried artists to canyon country — art fair meets outdoor recreation in one of the West\'s most dramatic settings.',
  },
  {
    title: 'Santa Fe Art Market',
    slug: 'santa-fe-art-market-2026',
    description: 'The Santa Fe Art Market, held annually in late July on the historic Santa Fe Plaza, is a juried outdoor art market that runs the weekend before the Indian Market — making late July the most concentrated period of gallery and market activity in the Santa Fe calendar. The market focuses on contemporary fine art and fine craft by living artists, with a strong Southwest regional emphasis alongside national exhibitors.',
    event_date: '2026-07-25',
    event_end_date: '2026-07-26',
    city_id: 6, state_code: 'NM', is_recurring: true,
    recurrence_rule: 'FREQ=YEARLY',
    is_free: true,
    website_url: 'https://www.santafeart.com',
    meta_title: 'Santa Fe Art Market 2026 | Juried Outdoor Market | Southwest Galleries',
    meta_description: 'The Santa Fe Art Market (July 2026) is a juried outdoor art market on the historic Plaza — the weekend before Indian Market, peak Santa Fe art season.',
  },
  {
    title: 'Denver Art Museum Free First Saturday',
    slug: 'denver-art-museum-free-first-saturday',
    description: 'The Denver Art Museum offers free general admission on the first Saturday of each month for Colorado residents. The museum\'s collection of 70,000+ objects — including one of the largest Native American art collections in the country and a landmark Daniel Libeskind-designed building — makes this one of the best free cultural offerings in the Rocky Mountain region. Family-friendly programming accompanies each free Saturday.',
    event_date: '2026-06-06',
    city_id: 9, state_code: 'CO',
    listing_id: 75, is_recurring: true,
    recurrence_rule: 'FREQ=MONTHLY;BYDAY=1SA',
    is_free: true,
    website_url: 'https://www.denverartmuseum.org',
    meta_title: 'Denver Art Museum Free First Saturday | Colorado Residents | Southwest Galleries',
    meta_description: 'Denver Art Museum offers free admission for Colorado residents on the first Saturday of every month — 70,000+ objects, Libeskind building, free family programming.',
  },
  {
    title: 'Tucson Meet Yourself',
    slug: 'tucson-meet-yourself-2026',
    description: 'Tucson Meet Yourself is an annual folk and traditional arts festival held each October on the University of Arizona Mall — free, three days, and one of the most genuinely multicultural public events in the Southwest. The festival celebrates the living folk art traditions of Tucson\'s diverse communities: Tohono O\'odham, Mexican, Chinese, African American, and beyond. Visual art exhibitions, craft demonstrations, and folk performance make it essential viewing for anyone interested in the living traditions that feed into the broader Southwest art scene.',
    event_date: '2026-10-09',
    event_end_date: '2026-10-11',
    city_id: 3, state_code: 'AZ', is_recurring: true,
    recurrence_rule: 'FREQ=YEARLY',
    is_free: true,
    website_url: 'https://www.tucsonmeetyourself.org',
    meta_title: 'Tucson Meet Yourself 2026 | Folk & Traditional Arts Festival | Southwest Galleries',
    meta_description: 'Tucson Meet Yourself (October 2026) is a free three-day folk and traditional arts festival celebrating the living cultural traditions of the Southwest.',
  },
  {
    title: 'Georgia O\'Keeffe Museum Research Center Lecture Series',
    slug: 'okeeffe-museum-lecture-series-2026',
    description: 'The Georgia O\'Keeffe Museum presents an annual lecture series at its Research Center in Santa Fe, bringing together scholars, artists, and critics for conversations about O\'Keeffe\'s work, the history of American Modernism, and the continuing influence of the Southwest on visual art. Lectures are held throughout the year and often coincide with the opening of temporary exhibitions at the museum.',
    event_date: '2026-09-10',
    city_id: 6, state_code: 'NM',
    listing_id: 49, is_recurring: true,
    recurrence_rule: 'FREQ=YEARLY',
    is_free: false,
    ticket_url: 'https://www.okeeffemuseum.org/events/',
    website_url: 'https://www.okeeffemuseum.org',
    meta_title: 'O\'Keeffe Museum Lecture Series 2026 | Santa Fe | Southwest Galleries',
    meta_description: 'The Georgia O\'Keeffe Museum Lecture Series (fall 2026) brings together scholars and artists for conversations about American Modernism and the Southwest art legacy.',
  },
  {
    title: 'Boulder Open Studios',
    slug: 'boulder-open-studios-2026',
    description: 'Boulder Open Studios, held each October, gives the public direct access to working artist studios across the city — over 200 artists open their spaces over two weekends. It\'s one of the largest open studio events in Colorado and an unparalleled opportunity to see work in progress, buy directly from makers, and have real conversations with artists about their practice. Boulder\'s strong arts and craft community makes this an exceptionally broad survey.',
    event_date: '2026-10-03',
    event_end_date: '2026-10-11',
    city_id: 11, state_code: 'CO', is_recurring: true,
    recurrence_rule: 'FREQ=YEARLY',
    is_free: true,
    website_url: 'https://www.boulderopenstudios.com',
    meta_title: 'Boulder Open Studios 2026 | Colorado Artist Studios | Southwest Galleries',
    meta_description: 'Boulder Open Studios (October 2026) opens 200+ artist studios across Boulder over two weekends — Colorado\'s premier open studio event.',
  },
  {
    title: 'Aspen Art Show',
    slug: 'aspen-art-show-2026',
    description: 'The Aspen Art Show, held in August in conjunction with the Aspen Music Festival, brings together gallery-quality work from exhibitors across the country in a tent structure in the heart of Aspen. The juried show focuses on painting and sculpture, with price points that range from accessible to investment-grade. The August timing — peak Aspen festival season — gives it one of the most financially serious collector audiences of any outdoor art fair in the country.',
    event_date: '2026-08-06',
    event_end_date: '2026-08-09',
    city_id: 10, state_code: 'CO', is_recurring: true,
    recurrence_rule: 'FREQ=YEARLY',
    is_free: false,
    ticket_url: 'https://www.aspenartshow.com',
    website_url: 'https://www.aspenartshow.com',
    meta_title: 'Aspen Art Show 2026 | Juried Fine Art | Southwest Galleries',
    meta_description: 'The Aspen Art Show (August 2026) is a juried fine art fair at peak festival season — gallery-quality painting and sculpture with a serious collector audience.',
  },
  {
    title: 'Las Vegas First Friday',
    slug: 'las-vegas-first-friday-arts-district',
    description: 'Las Vegas First Friday transforms the 18b Las Vegas Arts District on the last Friday of each month (6–10pm), with galleries opening simultaneously, live music, food trucks, and art installations filling the streets. The event is the anchor of downtown Las Vegas\'s arts community and draws a mix of locals and tourists to a neighborhood that offers something authentically creative amid the city\'s entertainment landscape.',
    event_date: '2026-05-29',
    city_id: 12, state_code: 'NV', is_recurring: true,
    recurrence_rule: 'FREQ=MONTHLY;BYDAY=-1FR',
    is_free: true,
    website_url: 'https://firstfridaylasvegas.org',
    meta_title: 'Las Vegas First Friday | 18b Arts District | Southwest Galleries',
    meta_description: 'Las Vegas First Friday happens the last Friday of every month in the 18b Arts District — galleries, live music, and the creative heart of downtown Las Vegas.',
  },
  {
    title: 'Phoenix Art Museum Free Night',
    slug: 'phoenix-art-museum-free-wednesday-night',
    description: 'The Phoenix Art Museum offers free admission every Wednesday evening from 3–9pm — one of the best deals in the Valley. With over 20,000 works spanning American, European, Asian, Latin American, and Western art, plus one of the country\'s finest fashion design collections, this is an institution that rewards repeat visits. The free Wednesday program has become a staple for Phoenix-area art lovers.',
    event_date: '2026-05-20',
    city_id: 4, state_code: 'AZ',
    listing_id: 33, is_recurring: true,
    recurrence_rule: 'FREQ=WEEKLY;BYDAY=WE',
    is_free: true,
    website_url: 'https://phxart.org',
    meta_title: 'Phoenix Art Museum Free Wednesday Night | Southwest Galleries',
    meta_description: 'Phoenix Art Museum is free every Wednesday evening (3–9pm) — 20,000+ works of art, free for all visitors.',
  },
];

async function run() {
  console.log(`Seeding ${events.length} events...`);
  for (const ev of events) {
    const [row] = await sql`
      INSERT INTO events (
        title, slug, description, event_date, event_end_date,
        start_time, end_time, city_id, state_code, listing_id,
        is_recurring, recurrence_rule, is_free, ticket_url,
        website_url, meta_title, meta_description
      ) VALUES (
        ${ev.title}, ${ev.slug}, ${ev.description},
        ${ev.event_date}, ${ev.event_end_date ?? null},
        ${ev.start_time ?? null}, ${ev.end_time ?? null},
        ${ev.city_id}, ${ev.state_code}::us_state, ${ev.listing_id ?? null},
        ${ev.is_recurring ?? false}, ${ev.recurrence_rule ?? null},
        ${ev.is_free ?? true}, ${ev.ticket_url ?? null},
        ${ev.website_url ?? null}, ${ev.meta_title ?? null}, ${ev.meta_description ?? null}
      )
      ON CONFLICT (slug) DO UPDATE SET
        title = EXCLUDED.title,
        description = EXCLUDED.description,
        event_date = EXCLUDED.event_date,
        event_end_date = EXCLUDED.event_end_date,
        meta_title = EXCLUDED.meta_title,
        meta_description = EXCLUDED.meta_description
      RETURNING id
    `;
    console.log(`  ✓ ${ev.title} (id: ${row.id})`);
  }

  const [count] = await sql`SELECT COUNT(*) FROM events`;
  console.log(`\nDone. ${count.count} events in DB.`);
}

run().catch(err => { console.error(err); process.exit(1); });
