const { neon } = require('@neondatabase/serverless');
const sql = neon(process.env.NEON_DB_KEY);

const guides = {
  'art-galleries-flagstaff-arizona': `<p>Flagstaff sits at 7,000 feet on the Colorado Plateau, surrounded by the world's largest ponderosa pine forest and within a day's drive of more national parks and monuments than anywhere else in the country. It is also a genuine college town anchored by Northern Arizona University, which produces a creative community of unusual depth and diversity for a city of 75,000. The gallery scene is more intimate than Sedona or Scottsdale, but the community is more authentic and the work more experimental — a place where artists are driven by the landscape and the culture rather than the tourist market.</p>

<h2>The Museum of Northern Arizona</h2>
<p>The Museum of Northern Arizona, founded in 1928 and located just north of downtown along Fort Valley Road, is the essential starting point for understanding the art and culture of the Colorado Plateau. Its collections span geology, biology, and the cultural heritage of the Hopi, Diné, Zuni, and other Indigenous peoples of the region, with a fine arts collection of particular strength in Hopi pottery, kachina figures, and Diné textiles. The museum's annual Heritage Festivals — dedicated in turn to Hopi, Diné, and Zuni cultures — bring artists from each community to sell work directly to the public in one of the most authentic contexts for collecting Indigenous art anywhere in the Southwest. These festivals, held each summer, are among the most important events on the Southwest Indigenous art calendar and draw serious collectors from across the country.</p>

<h2>The Cultural Context</h2>
<p>Flagstaff sits at a crossroads of cultures that shapes its art scene directly. The Diné Nation extends north and east across the Colorado Plateau; the Hopi mesas rise two hours away across high desert grassland; Havasupai, Hualapai, and Yavapai Apache homelands surround the city on other sides. This proximity is not incidental to Flagstaff's creative culture — it is central to it. Indigenous artists from these communities exhibit regularly at the Coconino Center for the Arts and the Museum of Northern Arizona, and their presence in the broader gallery ecosystem gives Flagstaff an authenticity of cultural grounding that tourist-oriented markets often lack. The Coconino Center for the Arts, operated by Coconino County in the Wheeler Park complex near Heritage Square, presents exhibitions with a deliberate emphasis on Indigenous and Southwestern voices alongside work by the broader regional contemporary community.</p>

<h2>Northern Arizona University</h2>
<p>The NAU Art Museum provides institutional context for contemporary practice, mounting exhibitions drawn from the university community and from regional and national artists whose work engages with the themes of the Colorado Plateau — landscape, ecology, Indigenous sovereignty, and the history of the American West. The university's art programs in painting, ceramics, printmaking, and digital arts produce a steady stream of emerging artists who bring formal rigor and fresh perspective to Flagstaff's creative community. Several outdoor sculptures and site-specific works installed across the NAU campus constitute a walkable public art collection worth visiting independently from the downtown gallery district.</p>

<h2>Downtown Gallery District</h2>
<p>The historic downtown along Route 66 and the surrounding streets contains a mix of galleries, studios, and artist-run spaces concentrated in the blocks between Leroux and Humphreys Streets. The downtown's well-preserved historic brick buildings from the railroad era of the 1880s and 1890s provide an appealing context for galleries that range from traditional Southwestern art to adventurous contemporary practice. The First Friday ArtWalk, held on the first Friday of each month from October through May, animates the downtown with openings and events that draw a primarily local audience — a useful indication that the art scene here serves a genuine community rather than a visiting one. Several studios operate open-door policies during ArtWalk, giving visitors access to working spaces and the opportunity to speak directly with artists about their practice.</p>

<h2>Regional Artists</h2>
<p>Flagstaff-based artists work in a wide range of media, but the specific landscape of the Colorado Plateau — the pine forests, the volcanic geology of the San Francisco Peaks, the extraordinary light that pours across the plateau at dawn and dusk — consistently reasserts itself as subject and influence. Painters working plein air in the high country around Flagstaff produce work that captures a quality of light and air distinctly different from the red-rock desert imagery associated with Sedona and Scottsdale. Ceramic artists in the region draw on the extraordinary Indigenous ceramic traditions of the surrounding Pueblo and Diné communities while developing contemporary approaches to the vessel and to sculptural form. Photographers working in the landscape around Flagstaff have access to subjects — the Painted Desert, the Petrified Forest, Monument Valley visible on the horizon — that are among the most photographed and least genuinely seen landscapes in the American West.</p>

<h2>Day Trip Context</h2>
<p>Flagstaff functions well as a base for exploring a remarkable arc of cultural sites. Walnut Canyon National Monument, 10 miles east on I-40, contains Sinagua cliff dwellings built into a limestone canyon around 1100 CE and visible from a one-mile island trail. Wupatki and Sunset Crater Volcanic Monument, 30 miles north, preserves additional Sinagua sites including a dramatic red sandstone pueblo. The South Rim of the Grand Canyon is 80 miles north. The Hopi mesas — First, Second, and Third Mesa — are two hours away across the Diné reservation and constitute the oldest continuously inhabited communities in North America, with artists selling directly from their homes and studios in a context unlike anything in the commercial gallery world.</p>

<h2>Practical Notes</h2>
<ul>
  <li>Flagstaff's altitude (6,910 feet) means genuine four-season weather: cool summers, real winters with significant snowfall, and spectacular fall color along the Peaks in October.</li>
  <li>Downtown parking is free after 6pm and on weekends along most streets.</li>
  <li>The Museum of Northern Arizona Heritage Programs schedule — including the Hopi, Diné, and Zuni festivals — is published on their website and worth planning a visit around.</li>
  <li>Driving north from Flagstaff on US-89 toward the Diné Nation opens onto Cameron Trading Post, one of the historic trading posts of the Southwest with a significant selection of Indigenous arts and craft.</li>
  <li>The Flagstaff Festival of Science (September) and the Flagstaff Mountain Film Festival (February) bring additional visitors and cultural programming that complement the arts calendar.</li>
</ul>`,

  'aspen-art-galleries-guide': `<p>Aspen is an unlikely art town in the best sense — a ski resort that has accumulated, over decades of serious wealth and cultural ambition, an art infrastructure that would be impressive in a city ten times its size. The Aspen Art Museum, designed by Shigeru Ban, is one of the most architecturally extraordinary and programmatically ambitious contemporary art institutions in the Mountain West. The commercial galleries surrounding it are fed by a collector base of unusual sophistication and purchasing power. And the Aspen Institute, one of the country's most significant cultural and ideas institutions, gives the city an intellectual ambition that goes well beyond the resort norm.</p>

<h2>The Aspen Art Museum</h2>
<p>The Aspen Art Museum moved into its current Shigeru Ban-designed building in 2014, and the building has become as discussed as the art inside it — a woven facade of Colorado spruce and composite that shifts appearance through the day as the mountain light changes. The institution presents six to eight exhibitions per year, with a strong emphasis on emerging and mid-career international artists at pivotal moments in their careers. There is no permanent collection, a deliberate choice that keeps programming perpetually fresh and allows the museum to take risks with artists who might not yet be represented in traditional encyclopedic collections. The rooftop sculpture garden offers views of the Elk Mountains that constitute one of the most beautiful outdoor art environments in America. Admission is always free.</p>

<h2>Commercial Galleries</h2>
<p>Aspen's commercial gallery scene is compact in geography but serious in quality. Ann Korologos Gallery is the most prestigious commercial space in town, with a program of major contemporary painters, sculptors, and photographers — work of national and international standing that would hold up in any major city. The gallery has represented artists shown at Frieze, Art Basel Miami Beach, and other leading international fairs, and summer season shows attract serious collector attention from across the country and Europe.</p>
<p>Baldwin Gallery has operated in Aspen for decades with a program focused on contemporary painting, sculpture, and photography by artists of national standing. The summer season programming is particularly strong, timed around the festival audiences that bring culturally engaged visitors to the city from late June through August.</p>
<p>Galerie Maximillian specializes in European modernism and works on paper — Picasso, Miró, Chagall, and their contemporaries — providing a counterpoint to the contemporary emphasis of the other leading galleries, with a deep inventory that serves collectors interested in the historical roots of modern practice. Beyond these anchors, Aspen supports a rotating population of seasonal galleries and pop-up exhibition spaces that appear during the summer festival period, creating a fluid gallery ecosystem that rewards exploratory walking along Hyman and Hopkins Avenues.</p>

<h2>The Aspen Institute</h2>
<p>The Aspen Institute, founded in 1949 by Chicago businessman Walter Paepcke and his wife Elizabeth, was conceived from the beginning as a place where ideas, art, and nature would coexist in an alpine setting of extraordinary beauty. Paepcke's founding vision — that serious thinking and aesthetic experience were inseparable pursuits — continues to animate Aspen's sense of itself. The Institute's Doerr-Hosier Center presents programming at the intersection of art, culture, and ideas throughout the summer, with talks and events that attract figures from politics, business, science, and the arts, creating an intellectual atmosphere that elevates the city's cultural life well beyond the resort baseline. Anderson Ranch Arts Center in nearby Snowmass Village, founded in 1966, provides one of the country's most respected artist residency and workshop programs in ceramics, woodworking, painting, and digital arts.</p>

<h2>The Festival Season</h2>
<p>Aspen's cultural calendar peaks from late June through August, when the Aspen Ideas Festival, the Aspen Music Festival and School, the Aspen Santa Fe Ballet, and a dense schedule of gallery openings compress into a few intense weeks. The Aspen Music Festival, in operation since 1949, brings hundreds of students and dozens of world-class performers for eight weeks of orchestral, chamber, and opera programming — creating a cultural density that extends into the galleries and studios. Many galleries bring in new work specifically for this period and schedule openings around festival audiences. If visiting Aspen for art, summer is the time to come. The concentration of quality work and the quality of the audience creates an environment where serious art conversations happen naturally.</p>

<h2>Public Art</h2>
<p>Aspen's public art program has placed significant works throughout the city — sculptures in Paepcke Park, installations along the Rio Grande Trail, and commissioned works on civic buildings that give the urban landscape a level of artistic attention rarely found in resort communities. Walking the city with attention to its public art reveals a depth of investment in the aesthetic quality of public space that reflects the original Paepcke vision: that a beautiful environment and serious culture are mutually reinforcing.</p>

<h2>Off-Season</h2>
<p>January and February see Aspen at its most intensely ski-focused, but several galleries remain open and the collector base is still in residence. The pace is slower and conversations with dealers more extended — a genuine advantage if building relationships rather than browsing. The winter light on snow-covered mountains has its own quality, and the works in gallery windows along Hyman Avenue look different in the blue winter light than they do in summer. Spring (April and May) is the quietest time, when galleries are preparing summer shows and the town briefly exhales — a rare opportunity to experience Aspen without crowds.</p>`,

  'las-vegas-art-galleries-guide': `<p>Las Vegas has a real art scene — not just decorative installations in casino lobbies, though those exist and some are worth attention. The Bellagio Gallery of Fine Art brings major traveling exhibitions from institutions like the Museum of Fine Arts Boston and the Art Institute of Chicago to the casino floor. The Neon Museum preserves the iconic signage of the city's visual history as genuine cultural artifacts. And the 18b Arts District in downtown has emerged as a genuine gallery neighborhood with a monthly art walk that draws thousands of locals. Las Vegas rewards the visitor who looks past the obvious.</p>

<h2>The Bellagio Gallery of Fine Art</h2>
<p>The Bellagio Gallery of Fine Art is Las Vegas's most important art venue — a serious institution operating inside one of the city's most famous hotels. Opened in 1998 as part of Steve Wynn's vision for a culturally aspirational Las Vegas, the gallery presents two to three traveling exhibitions per year drawn from major museum collections, and the quality is consistently high. Recent exhibitions have included Impressionist masterworks from private European collections, major 20th-century American photography, survey shows of significant sculptors, and thematic exhibitions organized around art historical periods and movements. The admission fee is modest and the experience is a genuine museum-quality encounter — quiet, climate-controlled, and thoughtfully installed in a space purpose-built for serious looking rather than casino distraction. The gallery has attracted millions of visitors since opening, many of them encountering significant art for the first time.</p>

<h2>The Neon Museum</h2>
<p>The Neon Museum is one of the most distinctive cultural institutions in the American Southwest — a salvage yard and exhibition space for the iconic neon signs that defined Las Vegas's visual identity from the 1940s through the 1990s. Located in downtown Las Vegas near the Fremont Street Experience, the boneyard of approximately 200 unrestored signs includes specimens from the Stardust, Caesars Palace, the Sahara, the Silver Slipper, and dozens of other legendary properties. Night tours — the primary way to experience the boneyard — illuminate the surviving neon against the dark sky, creating an experience that moves between elegy, spectacle, and genuine art historical encounter. The North Gallery, housed in the restored La Concha Motel lobby designed by architect Paul Revere Williams — one of the most prominent African American architects of the 20th century — provides indoor exhibition space for rotating shows that extend the museum's curatorial program beyond the boneyard itself.</p>

<h2>The 18b Las Vegas Arts District</h2>
<p>The 18b Las Vegas Arts District, centered on Charleston Boulevard and Main Street south of downtown, has been developing since the early 2000s and now contains a genuine mix of galleries, studios, antique dealers, coffee shops, and restaurants in a neighborhood that functions as Las Vegas's authentic creative community. The monthly First Friday Art Walk — held on the last Friday of every month from 6 to 10pm — has been running for over two decades, drawing thousands of visitors to gallery openings, studio tours, live music, and street performances in an atmosphere that is very Las Vegas: loud, festive, and genuinely local rather than tourist-oriented. Several galleries and the Contemporary Arts Center Las Vegas provide institutional anchors; around them, a rotating ecosystem of smaller spaces and studio open houses rewards patient exploration. The district is best experienced on foot; most of what matters is within a few blocks.</p>

<h2>Casino Art Collections</h2>
<p>Las Vegas's major hotels have invested hundreds of millions of dollars in art over the past three decades, and some of the most significant work in the city is in hotel lobbies and corridors rather than galleries or museums. The Aria Resort and Casino has assembled a particularly notable collection of site-specific commissions and sculpture, including works by Maya Lin, Jenny Holzer, Henry Moore, and Frank Stella — a collection that can be experienced on self-guided tours of the property. The Vdara Hotel and Waldorf Astoria feature large-scale installations throughout their public spaces. For visitors willing to navigate the casino floor, the art accessible across Las Vegas's major hotels constitutes an entirely separate and substantial gallery experience requiring no admission fee.</p>

<h2>Public Murals</h2>
<p>The Life is Beautiful music and arts festival, held in downtown Las Vegas each fall, has commissioned large-scale murals from internationally recognized street artists that have permanently transformed the urban fabric of the Fremont East Entertainment District. Walking the mural corridors along 6th, 7th, and 8th Streets reveals work by artists including Shepard Fairey, Augustine Kofie, and dozens of others, creating an outdoor gallery experience that extends the 18b Arts District north into the downtown core. The murals are free to view at any hour and constitute one of the most accessible art experiences in the city.</p>

<h2>What to Know</h2>
<p>Las Vegas does not have a strong commercial fine art market in the Santa Fe or Scottsdale sense — the collector base is largely transient and the gallery ecosystem reflects this reality. The city's art scene is best understood as a series of individual institutions and experiences rather than a coherent market serving a permanent collector community. Visit the Bellagio Gallery for quality traveling exhibitions, the Neon Museum for Las Vegas-specific cultural history, the 18b district for local creative community, and the casino hotel collections for large-scale contemporary commissions. Together they add up to considerably more than most visitors expect.</p>`,

  'southwest-folk-art-craft-galleries-guide': `<p>The American Southwest has one of the world's richest craft traditions — a three-way conversation between Indigenous, Spanish Colonial, and Anglo-American making that has been ongoing for centuries and continues to produce work of extraordinary quality and cultural depth. Finding the best of it requires knowing where to look and understanding what distinguishes the genuinely extraordinary from the simply decorative.</p>

<h2>The Museum of International Folk Art</h2>
<p>The Museum of International Folk Art in Santa Fe houses the world's largest collection of international folk art — over 130,000 objects from more than 100 countries — and serves as the essential institutional context for understanding the craft traditions of the Southwest. The permanent gallery, designed by Alexander Girard and installed in 1982, is one of the most visually overwhelming museum experiences in the Southwest: thousands of objects arranged in dense theatrical dioramas that reward slow, close looking. The New Mexican and Southwestern collections are particularly strong, with deep holdings in Hispanic tinwork, santos, and colcha embroidery alongside Indigenous pottery, basketry, and textile. The museum's special exhibitions regularly bring international craft traditions into dialogue with Southwestern ones, contextualizing local practice within a global history of making. A visit here before exploring the commercial gallery market pays dividends: the museum provides the historical and aesthetic framework that makes the best commercial galleries intelligible.</p>

<h2>Hispanic and Spanish Colonial Traditions</h2>
<p>New Mexico's Spanish Colonial craft tradition is among the oldest continuously practiced in North America. Santos — the carved and painted devotional figures produced by santeros for Catholic worship — have been made in New Mexico since the 18th century and remain a living tradition today. The Spanish Colonial Arts Society in Santa Fe maintains a collection and the annual Spanish Colonial Art Market held each July, which represents the finest contemporary santeros working in New Mexico. Several galleries on Canyon Road specialize in antique and contemporary santos, tinwork, and painted furniture. The Museum of Spanish Colonial Art, on Museum Hill in Santa Fe, presents the definitive collection of this tradition with historical depth and scholarly context unavailable anywhere else.</p>

<h2>Contemporary Studio Craft</h2>
<p>Mariposa Gallery in Albuquerque's Nob Hill neighborhood has been a leader in contemporary American studio craft since 1974 — one of the longest continuously operating craft galleries in the Southwest. The focus is studio jewelry, ceramics, glass, and fiber art by living artists, with an emphasis on work that uses craft traditions as a starting point for contemporary artistic investigation rather than as a constraint. The quality is consistently high, and the gallery has launched numerous artists who have gone on to national and international exhibition careers.</p>
<p>Santa Fe Clay operates as both an art school and a gallery dedicated entirely to ceramic arts — a dual focus that has made it an important gathering place for ceramicists at every level from student to internationally exhibited artist. The gallery program includes both utilitarian and sculptural work, and the school's visiting artist series regularly brings important figures to Santa Fe, generating an educational environment that has influenced the Southwest's ceramic arts community for decades.</p>

<h2>Studio Glass</h2>
<p>Philabaum Contemporary Art Glass in Tucson is among the country's leading venues for studio glass — a medium the Southwest has embraced with unusual enthusiasm given its tradition of working with light and color in all media. The technical ambition of the work goes well beyond decorative intent; several represented artists show in major museum exhibitions and are collected by institutions including the Smithsonian's Renwick Gallery. The Southwest's exceptional light has attracted glassblowers who find the region's visual environment uniquely sympathetic to their medium's expressive possibilities.</p>

<h2>Trading Posts and Markets</h2>
<p>The Southwest's historic trading posts — Cameron Trading Post north of Flagstaff, Hubbell Trading Post National Historic Site in Ganado, Arizona, and others throughout the Diné Nation — provide access to Indigenous-made work in a context that predates the commercial gallery system and operates by different rules. Hubbell, operated by the National Park Service, sells work by Diné weavers directly in a historic post that has been facilitating trade since 1876. The annual Indigenous art markets in Santa Fe each August and the Heard Museum's annual market in Phoenix are the most important public events for collecting Indigenous craft at the highest level, bringing together artists of demonstrated quality in a curated, competitive context.</p>

<h2>Chimayó and the Northern Villages</h2>
<p>The small communities of northern New Mexico — Chimayó, Truchas, Cordova, Trampas — sustain craft traditions of extraordinary depth in weaving, woodcarving, and embroidery that date to the Spanish colonial period. Ortega's Weaving Shop in Chimayó has been producing Rio Grande-style blankets and rugs on traditional looms since 1900. The village of Cordova is known for unpainted santos and animal figures carved in the local cottonwood root — work of severe economy and expressive power. These village traditions are not primarily oriented toward tourist consumption; they exist because the communities that maintain them value the making. Visiting respectfully and buying directly from makers is the most meaningful way to engage with this aspect of Southwestern craft culture.</p>

<h2>What to Look For</h2>
<p>In the Southwest craft market, provenance and authentication matter differently than they do for fine art. For traditional Indigenous work, federal law requires that work sold as Indigenous-made be produced by a tribally enrolled or certified artist — a legal protection that has not eliminated fraudulent work but gives buyers legal recourse. Always ask galleries and vendors for artist information: name, tribal affiliation, and any relevant certifications or exhibition history. For contemporary studio work, artist statements and exhibition history are the relevant markers of quality. The distinction between fine craft and folk art — never stable anywhere — is particularly blurred in the Southwest, which creates opportunity for collectors willing to look past category labels and focus on the work itself.</p>`,

  'phoenix-art-galleries-first-friday-guide': `<p>Phoenix has spent the past decade building an arts infrastructure worthy of a major American city, and the investment is paying off in tangible ways. The Roosevelt Row Arts District has developed into a genuine creative neighborhood of studios, galleries, and artist residencies. The Phoenix Art Museum has expanded its collection and programming significantly. And the monthly First Friday Art Walk has become one of the most attended gallery events in the American Southwest, drawing thousands of visitors to a neighborhood that is genuinely becoming what city arts districts only sometimes manage to be. Here is how to navigate it all.</p>

<h2>The Phoenix Art Museum</h2>
<p>The Phoenix Art Museum is one of the largest art museums in the American West, with a permanent collection of over 20,000 works spanning American, European, Asian, Latin American, and Western art in more than 250,000 square feet of gallery space. The museum has made serious investments in its contemporary collection over the past decade, with significant acquisitions in painting, works on paper, and media art by artists of national and international standing. The Fashion Design collection — rarely cited in mainstream art coverage but genuinely extraordinary in scope and quality — is one of the finest collections of couture and fashion history in the United States, with works spanning more than a century of design. The Latin American collection has been strengthened considerably, reflecting Phoenix's cultural reality as a majority-minority city with deep historical connections to Mexico and the broader Latin American world. The museum is a mandatory stop regardless of what else you do in Phoenix.</p>

<h2>The Heard Museum</h2>
<p>The Heard Museum is among the world's foremost institutions dedicated to Indigenous art and culture — an institution of extraordinary scope and depth located just north of downtown Phoenix. The permanent exhibition on the Indigenous boarding school era presents the history of forced assimilation through the voices and art of those who survived it, making it one of the most honest and affecting museum experiences in the American West. The Heard's collection of Hopi kachina figures is the finest in the world, numbering over 6,000 carved and painted figures spanning more than a century of artistic production. The museum's annual market, held each spring, brings Indigenous artists from across the country to sell work directly to the public in a curated, competitive context. The museum shop carries work by represented artists at prices that reflect the actual cost of handmade art rather than the tourist markup that inflates prices elsewhere.</p>

<h2>Roosevelt Row</h2>
<p>The Roosevelt Row Arts District, centered on Roosevelt Street between 1st and 7th Avenues, is Phoenix's most active and evolving gallery neighborhood. Rising rents in coastal cities have pushed artists and galleries toward Phoenix's more affordable footprint over the past decade, and the quality of work being shown has risen correspondingly. Modified Arts, one of the district's longest-operating galleries, occupies a converted auto shop and combines exhibition programming with music and performance events — an approach that reflects the district's community-building ambitions as much as its commercial ones. Perihelion Arts takes a more formally ambitious approach, presenting exhibitions that engage seriously with current critical discourse. Eye Lounge, the district's most important cooperative gallery, provides exhibition space for emerging Phoenix-based artists in a community-driven rather than market-driven context. Several studio buildings along the corridor give visitors the opportunity to encounter artists at work on gallery walk nights.</p>

<h2>First Friday</h2>
<p>The First Friday Art Walk happens on the first Friday of every month from 6 to 10pm, and on the best nights it transforms Roosevelt Row into one of the most energetic public art events in the Southwest. Galleries schedule exhibition openings around the event, food trucks and street vendors fill the sidewalks, and live music spills out of studios and alternative spaces. The crowd is young, diverse, and genuinely local — the event functions as a community gathering as much as an art walk, which is both its strength and its limitation as a purely art-viewing context. Serious collectors and gallery visitors learn to visit individual galleries on quieter evenings and use First Friday for discovering new spaces and meeting artists at openings. October through April produces the best attendance; summer heat reduces crowds but never eliminates the event.</p>

<h2>Scottsdale and the Valley</h2>
<p>Phoenix and Scottsdale share a metro area, and serious art visitors usually cover both. The Scottsdale Arts District — centered on Marshall Way and Main Street in Old Town — is one of the country's largest concentrations of fine art galleries, specializing in Western American painting, bronze sculpture, and the work of Indigenous artists from across the Southwest. The Scottsdale ArtWalk on Thursday evenings, running October through May, provides a dedicated gallery walk format that complements Phoenix's First Friday. The Scottsdale Museum of Contemporary Art presents a serious program of traveling exhibitions. Planning a long weekend to cover both cities — adding the Heard Museum on a morning and the Phoenix Art Museum on another day — gives a comprehensive picture of one of the most dynamic art markets in the American West.</p>

<h2>Collecting in Phoenix</h2>
<p>Phoenix's art market has become increasingly significant as the city has grown. Galleries in both Phoenix and Scottsdale offer work at a wider range of price points than the market's reputation for high-end Western art suggests — alongside blue-chip works, there is accessible, high-quality art by emerging and mid-career Arizona artists available at prices that reward early attention. The annual Scottsdale Art Auction, held each spring, is one of the most important events in the Western American art secondary market and provides an index of current prices and collector appetite worth monitoring even for those not actively buying. Phoenix's growing base of younger collectors, drawn by the city's rapid growth and relatively low cost of living compared to coastal markets, is beginning to create the kind of sustained demand that allows a gallery ecosystem to deepen over time.</p>`,

  'southwest-photography-galleries-guide': `<p>The American Southwest has been central to the history of fine art photography since the medium's earliest days in North America. Timothy O'Sullivan's survey photographs of the Colorado Plateau in the 1870s are among the most important documents in American visual history. Ansel Adams spent decades here perfecting a technical and aesthetic vision of the Western landscape that shaped photography's ambitions for a generation. Edward Weston, Laura Gilpin, and Dorothea Lange all found essential subjects in the region. Today, several galleries and institutions in the Southwest specialize in photography at the highest level — spaces where photographs are the main event, not an afterthought to painting and sculpture.</p>

<h2>Etherton Gallery, Tucson</h2>
<p>Etherton Gallery in Tucson is, by most assessments, the most important photography gallery in the Southwest — a 40-year institution with a permanent program of vintage and contemporary work and secondary market inventory of genuine depth and scholarly seriousness. Founded by Terry Etherton in 1981, the gallery has built its reputation on a dual commitment to historical photography of the American West — O'Sullivan, Jackson, Vroman, Wittick — and to contemporary photographers working at the intersection of documentary practice and fine art. The gallery represents living photographers alongside estate sales and vintage prints by historical figures, and the scholarship behind the programming is serious: condition reports, edition documentation, and provenance research are standard parts of gallery communication. If you are collecting photography in the Southwest, Etherton is the essential starting point and the benchmark against which other galleries should be measured.</p>

<h2>Photo Eye Gallery, Santa Fe</h2>
<p>Photo Eye Gallery in Santa Fe operates alongside the Photo Eye bookstore — one of the world's great photography bookshops, with an inventory spanning the full history of the medium — and presents a program focused on contemporary photographers of national and international standing. The combination of gallery and bookshop creates an unusually rich context for the work on display: the books provide the criticism, the history, and the broader conversation that wall labels necessarily compress. Photo Eye has championed photographers engaging with portraiture, landscape, documentary practice, and conceptual approaches, consistently presenting work that takes the medium seriously as an art form. Exhibition programming runs year-round, with openings during the high gallery season of summer and early fall drawing collectors and photography enthusiasts from across the country.</p>

<h2>Andrew Smith Gallery, Santa Fe</h2>
<p>Andrew Smith Gallery specializes in 19th and early 20th-century photography with particular depth in American West survey and exploration images — O'Sullivan, Jackson, Hillers, Watkins — as well as the major 20th-century figures who worked in the region, including Adams, Weston, and Gilpin. For collectors interested in historical photography, the inventory is extraordinary in both depth and quality. Smith has built relationships with major collections and estates over decades, giving the gallery access to significant vintage prints that rarely appear on the open market. The gallery also handles photographic books, albums, and ephemera that provide essential context for understanding the history of the medium in the West.</p>

<h2>The History of Southwest Photography</h2>
<p>Understanding the photography sold in Southwest galleries requires some knowledge of the medium's distinctive history in the region. The survey photographs of O'Sullivan and Jackson in the 1870s were made as scientific documents for government surveys — but their aesthetic power has made them among the most studied images in American art history. Laura Gilpin spent 50 years documenting the Diné Nation with a combination of technical mastery and genuine cultural engagement that distinguished her work from the extractive ethnography of many contemporaries. Ansel Adams's relationship with the Southwest — beginning with his time at the Grand Canyon in the 1920s and extending through his friendship with Georgia O'Keeffe — produced some of the most recognized images in photography's history. Indigenous photographers working today, including Will Wilson and Cara Romero, extend this history into the present with work that reclaims the camera as an instrument of self-representation rather than external documentation.</p>

<h2>Photography in the Broader Market</h2>
<p>Beyond the specialist galleries, significant photography appears throughout the Southwest commercial gallery ecosystem. Renee Taylor Gallery in Sedona and Exposures International Gallery carry substantial photography inventories alongside painting and sculpture. The Scottsdale Museum of Contemporary Art regularly features photography in its traveling exhibitions. The Center for Creative Photography at the University of Arizona in Tucson — one of the world's great photography archives — holds the archives of Ansel Adams, Weston, and dozens of other major figures, and presents periodic public exhibitions drawn from these extraordinary holdings. The Heard Museum's collection contains important documentary and fine art photography by Indigenous photographers whose work is increasingly recognized as central to the medium's history in the Southwest.</p>

<h2>Collecting Photography</h2>
<p>Fine art photography has a pricing structure that rewards early attention and punishes late entry into an artist's market. Vintage prints — photographs made close in time to the original negative — command premiums over later printings of the same image, because they carry evidence of the original printing decision and reflect the photographer's own darkroom choices. Edition size matters for contemporary photographers: smaller, strictly limited editions hold value better than open editions or very large ones. Condition is paramount; photographic materials degrade from light exposure in ways that are difficult to reverse, and condition problems that seem minor can significantly affect value. Ask any serious gallery about provenance, edition status, condition, and authentication policy before purchasing. The specialist galleries listed here — Etherton, Photo Eye, Andrew Smith — are transparent about all of these factors, and their educational approach to clients is a significant part of their value to the collecting community.</p>`,
};

async function run() {
  const slugs = Object.keys(guides);
  console.log(`Expanding ${slugs.length} guides...`);
  for (const slug of slugs) {
    const result = await sql`UPDATE posts SET content = ${guides[slug]} WHERE slug = ${slug} RETURNING title`;
    const title = result[0]?.title ?? slug;
    const wordCount = Math.round(guides[slug].replace(/<[^>]+>/g, ' ').split(/\s+/).filter(Boolean).length);
    console.log(`  ✓ ${title} (~${wordCount} words)`);
  }
  console.log('Done.');
}

run().catch(console.error);
